services:

  traefik:
    image: "traefik:v3.3"
    #image: "traefik:v2.11.22"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--experimental.localPlugins.traefik-maintenance.modulename=github.com/azzu/traefik-maintenance"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./plugins-local/:/plugins-local/"

  whoami_t:
    image: "nginx:latest"
    container_name: "trigger-test"
    volumes:
      - "./plugins-local/src/github.com/azzu/traefik-maintenance/maintenance.html:/usr/share/nginx/html/maintenance.html"
      - "./plugins-local/src/github.com/azzu/traefik-maintenance/maintenance.json:/usr/share/nginx/html/maintenance.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.trigger.rule=Host(`trigger.localhost`)"
      - "traefik.http.routers.trigger.entrypoints=web"
  
  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami1.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami1.entrypoints=web"
      - "traefik.http.routers.whoami1.middlewares=redirectall"
      - "traefik.http.routers.whoami1.middlewares=maintenance1"
      - "traefik.http.middlewares.redirectall.redirectregex.regex=^http://whoami.localhost/r/(.*)"
      - "traefik.http.middlewares.redirectall.redirectregex.replacement=https://store.hanssem.com/$${1}"
      - "traefik.http.middlewares.redirectall.redirectregex.permanent=false"
      - "traefik.http.middlewares.maintenance1.plugin.traefik-maintenance.enabled=true"
      - "traefik.http.middlewares.maintenance1.plugin.traefik-maintenance.fileName=http://trigger.localhost/maintenance.html"
      - "traefik.http.middlewares.maintenance1.plugin.traefik-maintenance.triggerUrl=http://trigger.localhost"
      - "traefik.http.middlewares.maintenance1.plugin.traefik-maintenance.httpResponseCode=200"
      - "traefik.http.middlewares.maintenance1.plugin.traefik-maintenance.httpContentType=text/html; charset=utf-8"
      - "traefik.http.routers.whoami2.rule=Host(`whoami.localhost`) && PathPrefix(`/API`)"
      - "traefik.http.routers.whoami2.middlewares=maintenance2"
      - "traefik.http.middlewares.maintenance2.plugin.traefik-maintenance.enabled=true"
      - "traefik.http.middlewares.maintenance2.plugin.traefik-maintenance.fileName=http://trigger.localhost/maintenance.json"
      - "traefik.http.middlewares.maintenance2.plugin.traefik-maintenance.triggerUrl=http://trigger.localhost"
      - "traefik.http.middlewares.maintenance2.plugin.traefik-maintenance.httpResponseCode=200"
      - "traefik.http.middlewares.maintenance2.plugin.traefik-maintenance.httpContentType=application/json"
